# Generated by Django 3.2.12 on 2022-04-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='Latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='Longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
